import com.terahorse.fobit.model.Game
import com.terahorse.fobit.model.Player

rule "currentRound: increase round"
    dialect "mvel"
    agenda-group "SETUP"
when
    $g: Game()
then
    modify($g){
        currentRound = $g.currentRound + 1
    }
end

rule "currentRound: max value"
    dialect "mvel"
    agenda-group "SETUP"
when
    $g: Game(currentRound > maxRounds)
then
    modify($g){
        currentRound = $g.maxRounds,
        running = false
    }
end

rule "remainingAttacks: reload"
    dialect "mvel"
    agenda-group "SETUP"
when
    $p: Player(alive, attacking)
then
    modify($p){
        remainingAttacks = $p.speed
    }
end
